# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
#
# # Define a job to be invoked later in a workflow.
# # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# jobs:
#   say-hello:
#     # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
#     # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
#     docker:
#       - image: cimg/ruby:2.7-node
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#       - image: mcr.microsoft.com/mssql/server:2019-latest
#         environment:
#           SA_PASSWORD: <YourStrong@Passw0rd>
#           ACCEPT_EULA: Y
#     # Add steps to the job
#     # See: https://circleci.com/docs/2.0/configuration-reference/#steps
#     steps:
#       - checkout
#       - run:
#           name: "ruby"
#           command: "ruby -v"
#
# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   say-hello-workflow:
#     jobs:
#       - say-hello


version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y imagemagick libmagickwand-dev
      - ruby/install-deps
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.5
      - image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
      MYSQL_USER: root
      MYSQL_HOST: 127.0.0.1
      MYSQL_DATABASE: mediprocity_test
      MYSQL_ROOT_PASSWORD: password
      APN_KEY: dummy
      APN_KEY_ID: dummy
      APN_TEAM_ID: dummy
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: echo 127.0.0.1 db | sudo tee -a /etc/hosts
      - run: cp ./config/database.yml.example ./config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:create db:schema:load
      - run: bundle exec rspec
      - run: bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
